repos:
- repo: https://github.com/terraform-docs/terraform-docs
  rev: "v0.18.0"
  hooks:
  - id: terraform-docs-go
    args: ["-c",".terraform-docs.yml","."]
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: "v1.92.0"
  hooks:
  - id: terraform_validate
    args:
    - --hook-config=--retry-once-with-cleanup=true
  - id: terraform_fmt
  - id: terraform_tflint
  - id: terraform_trivy

